language: cpp

os:
  - linux
  - osx

dist: xenial

osx_image: xcode12.2

git:
  depth: false

addons:
  apt:
    packages:
      - qtbase5-dev
      - qttools5-dev-tools
      - libqt5opengl5-dev
      - libusb-1.0-0-dev
      - libfftw3-dev
  homebrew:
    packages:
      - fftw

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CMAKE_PREFIX_PATH=$(brew --prefix qt5); fi

before_script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH ../

script:
 - make -j4

before_deploy:
 - sudo make package

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: packages/*
  on:
    tags: true
